export const FETCH_ALL_TODOS_STARTED = 'FETCH_ALL_TODOS_STARTED';
export const FETCH_ALL_TODOS_SUCCESS = 'FETCH_ALL_TODOS_SUCCESS';

export const FETCH_COMPLETED_TODOS_STARTED = 'FETCH_COMPLETED_TODOS_STARTED';
export const FETCH_COMPLETED_TODOS_SUCCESS = 'FETCH_COMPLETED_TODOS_SUCCESS';

export const UPDATE_TODO_STARTED = 'UPDATE_TODO_STARTED';
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';