export const FETCH_ALL_TODOS_STARTED = 'FETCH_ALL_TODOS_STARTED';
export const FETCH_ALL_TODOS_SUCCESS = 'FETCH_ALL_TODOS_SUCCESS';

export const CREATE_TODO_STARTED = 'CREATE_TODO_STARTED';
export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS';